############################
## CHANGE THESE
############################

baseURL: 'https://bayoumountain.holdings'
title: 'Bayou Mountain Holdings, LLC'

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'
enableRobotsTXT: true

markup:
  _merge: deep
  goldmark:
     renderer:
       unsafe: true
