############################
## CHANGE THESE
############################

baseURL: 'https://bayousno.co'
title: 'Bayou Sno Co.'

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'
enableRobotsTXT: true

markup:
  _merge: deep
  goldmark:
     renderer:
       unsafe: true
