# --- FINAL, WORKING wrangler.toml STRUCTURE ---

name = "bayoumountain" 
pages_build_output_dir = "public"

# D1 Database Definition (Top-Level)
[[d1_databases]]
binding = "DB"
database_name = "bmhforms"
database_id = "cb9d6ef7-7545-4142-9c12-3802df59055d" 

# Pages Functions Configuration Block
[pages_functions]
    # Bindings Array - This is the array that applies bindings to your function.
    [[pages_functions.bindings]]
    name = "MAIL_SERVICE"
    type = "email"
    value = "forms@bayoumountain.holdings"