# --- Example wrangler.toml ---

name = "bayoumountain" 
pages_build_output_dir = "public"

# Existing Mail Binding
[[bindings]]
name = "MAIL_SERVICE"
type = "email"
value = "forms@bayoumountain.holdings" # Use your actual sender email

# New D1 Binding
[[d1_databases]]
binding = "DB" # This is the variable name used in your function code (env.DB)
database_name = "bmhforms" # Use the exact name from Step 1
# You do NOT need a database_id for Pages functions configured in wrangler.toml

# --- End example wrangler.toml ---