# --- Example wrangler.toml ---

name = "bayoumountain" 
pages_build_output_dir = "public"

# Existing Mail Binding
[[bindings]]
name = "MAIL_SERVICE"
type = "email"
value = "forms@bayoumountain.holdings" # Use your actual sender email

# New D1 Binding - Must include the database_id
[[d1_databases]]
binding = "DB" # The variable name used in your function (env.DB)
database_name = "bmhforms" # The name you chose
database_id = "cb9d6ef7-7545-4142-9c12-3802df59055d" 

# --- End example wrangler.toml ---